module.exports = {
    STORE_KEY: 'a56z0fzrNpl^2',
    screen :'',
    time : 0,
    BASE_URL: 'https://yawd.in/admin_old/api/customers/',
    //BASE_URL: 'http://www.thenewsmen.co.in/newsmentest/admin/api/',
    home :'HomeScreen',
    Signin :'LoginScreen',
    Signup :'SignupScreen',
    user_id:'',
    mobile:'',
    allservice:[],
    gender:'',
    package:'',
    token:'',
    total:'',
    firebaseToken:'',
    sum:'',
    cart:[],
    address:'',
    lat:'',
    long:'',
    add_id:'',
    time:'',
    date:'',
    profile:'',
    mode:'',
    booking:'',
    type:'',
    shop:'',
    cat:'',
    shop_id:'',
    cat1:'',
    sum_id:'',
    min_pay:'',
    wallet:'',
    house:'',
    reshed_date:'',
    reshed_time:'',
    shopping:'',
    draw:'',
    ref:'',
    dukan_id:'',

    
    
    COLOR: {
        ORANGE: '#C50',
        DARKBLUE: '#0F3274',
        LIGHTBLUE: '#6EA8DA',
        DARKGRAY: '#999',
    },
};